### ISSUE TITLE
Database structure example

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#99]
Example:

```toml

# This is a TOML document for all files related to global-scale
# inversions at Princeton University.

title = "Global Adjoint Inversions"
base = "/projects/TROMP"

[owner]
name = "Princeton Geosciences"
dob = 2022-03-14T00:32:00-08:00 # First class dates

########################################################################################
# This category provides descriptions of different models obtained from various methods
[structure]

  [structure.adjoint]
  folder = "Global_Adjoint_Tomography"
  stations = 'stations' # directory where stations are stored for every event
  events = 'events'  # updated CMTSOLUTION files
  raw_obsd = 'raw_obsd' # raw observed waveforms
  raw_synt = 'raw_synt' # synthetics to all raw data irrespective of whether used in inversion
  proc_obsd = 'proc_obsd' # differential measuremnts between observed and synthetics
  proc_synt = 'proc_synt' # synthetics
  data = 'data' # folder where data used in the model is stored
  model = 'model' # folder where model evaluations are stored in various formats
  pre_filt="{'17_40':[0.0188, 0.0250, 0.0588, 0.0735],'40_100':[1/125., 1/100., 1/40., 1/32]}" # frequency band for filetrr in Hz 13.7-17-40-53

  windows_folder = 'windows' # filter windows used
  taper_type = 'hann'
  taper_percentage = 0.05


    [structure.adjoint.M25]
    folder = 'M25'
    citation = "Lei et al., 2021"

    [structure.adjoint.M00]
    folder = 'MOO'
    citation = "Kustowski et al., 2008"

  [structure.fst]
  folder = "Full_Spectrum_Tomography"
  data = 'data' # folder where data used in the model is stored
  model = 'model' # folder where model evaluations are stored in various formats
  proc_synt = 'proc_synt' # synthetics

    [structure.fst.S362ANI_M]
    folder = 'S362ANI+M'

########################################################################################

```
